name: 'Find-and-replace on branch names'
description: 'Finds and replaces text on branch names'
inputs:
  strings:
    description: 'The text you want to run this action on'
    required: true
  find:
    description: 'The text you're looking for'
    required: true
  replace:
    description: 'The text you want to replace with'
    required: true
outputs:
  value:
    description: 'The new value after find-and-replace has been run'
runs:
  using: 'node12'
  main: 'index.js'
